[package]
name = "thracer"
version = "0.1.0"
authors = ["youness_kafia"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.19.0"
image = "0.22.4"